/*
 * Asset lookup with placeholders.
 *
 * Every image is referenced by id ('avatar/owlet-boy/idle', 'creature/lobstorian/idle',
 * 'scene/fair'). data/assets.js (generated by tools/build-assets.mjs) maps ids to
 * files and native sizes. Until art exists, Rift.Assets.img() returns a labelled
 * silhouette card in the right colour, so the whole game is playable without art.
 */
(function (root) {
    'use strict';

    const Rift = root.Rift;
    const BASE = 'assets/';

    function manifest() {
        return (Rift.data && Rift.data.assets) || {};
    }

    function has(id) {
        return !!manifest()[id];
    }

    function url(id) {
        const entry = manifest()[id];
        return entry ? BASE + entry.file : null;
    }

    // Placeholder art: an SVG data URL with a soft silhouette, a glow in the
    // owner's colour and the id written small, so missing art is obvious but
    // the screen still reads well.
    const SHAPES = {
        avatar: 'M50 18c14 0 24 11 24 25 0 9-4 16-10 20l6 27H30l6-27c-6-4-10-11-10-20 0-14 10-25 24-25z',
        creature: 'M50 15c18 0 30 14 30 30 0 12-6 21-14 26l4 19H30l4-19c-8-5-14-14-14-26 0-16 12-30 30-30zM28 22l-8-10 14 4zM72 22l8-10-14 4z',
        npc: 'M50 16c13 0 22 10 22 23 0 9-5 16-11 20l14 31H25l14-31c-6-4-11-11-11-20 0-13 9-23 22-23z',
        item: 'M50 20l22 14v32L50 80 28 66V34z',
        scene: null,
    };

    function placeholderSvg(id, opts) {
        const o = opts || {};
        const kind = id.split('/')[0];
        const hex = o.colour ? (Rift.COLOURS[o.colour] || {}).hex || o.colour : '#B0219E';
        const label = (o.label || id.split('/').slice(1).join(' ')).replace(/[<>&"]/g, '');
        const w = o.width || (kind === 'scene' ? 1600 : 100);
        const h = o.height || (kind === 'scene' ? 900 : 120);
        let body;
        if (kind === 'scene') {
            body = `<defs><radialGradient id="g" cx="50%" cy="35%" r="75%"><stop offset="0" stop-color="${hex}" stop-opacity=".35"/><stop offset="1" stop-color="#0F1F1A"/></radialGradient></defs>`
                + `<rect width="${w}" height="${h}" fill="url(#g)"/>`
                + `<path d="M0 ${h * 0.78} Q ${w * 0.25} ${h * 0.7} ${w * 0.5} ${h * 0.78} T ${w} ${h * 0.75} V ${h} H0z" fill="#081410" opacity=".85"/>`
                + `<text x="50%" y="46%" fill="#EFE3C8" opacity=".55" font-family="Georgia,serif" font-size="${Math.round(h / 14)}" text-anchor="middle">${label}</text>`;
        } else {
            const shape = SHAPES[kind] || SHAPES.creature;
            body = `<defs><radialGradient id="g" cx="50%" cy="45%" r="55%"><stop offset="0" stop-color="${hex}" stop-opacity=".7"/><stop offset="1" stop-color="${hex}" stop-opacity="0"/></radialGradient></defs>`
                + `<ellipse cx="50" cy="52" rx="46" ry="50" fill="url(#g)"/>`
                + `<path d="${shape}" fill="#1A1020" stroke="${hex}" stroke-width="2.5"/>`
                + `<text x="50" y="112" fill="#EFE3C8" font-family="Georgia,serif" font-size="9" text-anchor="middle">${label.slice(0, 22)}</text>`;
        }
        const viewBox = kind === 'scene' ? `0 0 ${w} ${h}` : '0 0 100 120';
        return 'data:image/svg+xml;utf8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`);
    }

    function src(id, opts) {
        return url(id) || placeholderSvg(id, opts);
    }

    function img(id, opts) {
        const o = opts || {};
        const node = Rift.el('img', { src: src(id, o), alt: o.alt || '', draggable: false, className: o.className || '' });
        if (!has(id)) node.dataset.placeholder = id;
        return node;
    }

    // Sprite-sheet frames (walk cycles): manifest entry { file, frames, frameWidth, frameHeight }
    function frames(id) {
        const entry = manifest()[id];
        return entry && entry.frames ? entry : null;
    }

    Rift.Assets = { has, url, src, img, frames, placeholderSvg };
})(typeof window !== 'undefined' ? window : globalThis);
