// Render the ElevenLabs sound-effect plan (tools/sfx-plan.mjs) to assets/sfx/el/ and write data/sfx-el.js.
// Costs about 10 credits per second of sound (free plan: 10,000 credits a month). Existing files are kept.
//
//   node tools/sfx-eleven.mjs              status and estimated cost of what is missing
//   node tools/sfx-eleven.mjs --render     render what is missing (add --only <prefix> to limit)
//   node tools/sfx-eleven.mjs --redo <file-stem>   delete and re-render one file, e.g. cr-keanu-enter-2
//
// Key: .secrets/elevenlabs_api_key at the repo root; read here only, never printed or shipped.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PLAN } from './sfx-plan.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GAME = path.resolve(HERE, '..');
const KEY_FILE = path.resolve(GAME, '..', '..', '..', '.secrets', 'elevenlabs_api_key');
const OUT = path.join(GAME, 'assets', 'sfx', 'el');
const DATA = path.join(GAME, 'data', 'sfx-el.js');
const USAGE = path.join(HERE, 'eleven-usage.json');

const args = process.argv.slice(2);
const opt = n => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : null; };

const jobs = PLAN.flatMap(([name, secs, prompt, n]) => Array.from({ length: n }, (_, i) => ({ name, stem: name + '-' + (i + 1), secs, prompt })));
const file = j => path.join(OUT, j.stem + '.mp3');

function logUse(id, credits) {
    const u = fs.existsSync(USAGE) ? JSON.parse(fs.readFileSync(USAGE, 'utf8')) : { total: 0, calls: [] };
    u.note = 'Credits per call from the character-cost header (sound effects since 10 Oct). Free plan about 10,000 a month.';
    u.total += credits; u.calls.push({ at: new Date().toISOString(), kind: 'sfx', id, chars: credits });
    fs.writeFileSync(USAGE, JSON.stringify(u, null, 2));
}

async function render(j) {
    const res = await fetch('https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_64', {
        method: 'POST', signal: AbortSignal.timeout(120000),
        headers: { 'xi-api-key': fs.readFileSync(KEY_FILE, 'utf8').trim(), 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: j.prompt, duration_seconds: j.secs, prompt_influence: 0.45 }),
    });
    if (!res.ok) throw new Error(res.status + ' ' + (await res.text()).slice(0, 300));
    fs.writeFileSync(file(j), Buffer.from(await res.arrayBuffer()));
    const cost = +res.headers.get('character-cost') || Math.ceil(j.secs * 10);
    logUse(j.stem, cost);
    return cost;
}

function writeData() {
    const map = {};
    for (const j of jobs) if (fs.existsSync(file(j))) (map[j.name] ||= []).push('el/' + j.stem + '.mp3');
    fs.writeFileSync(DATA, `/*
 * ElevenLabs sound effects (generated by tools/sfx-eleven.mjs from tools/sfx-plan.mjs; do not edit).
 * Adds names to Rift.data.sfx; a name with several files picks one at random.
 */
(function (root) {
    'use strict';
    Object.assign(root.Rift.data.sfx, ${JSON.stringify(map, null, 4).replace(/\n/g, '\n    ')});
})(typeof window !== 'undefined' ? window : globalThis);
`);
    return Object.values(map).flat().length;
}

async function main() {
    fs.mkdirSync(OUT, { recursive: true });
    if (opt('--redo')) { const f = path.join(OUT, opt('--redo') + '.mp3'); if (fs.existsSync(f)) fs.unlinkSync(f); }
    const only = opt('--only') || (opt('--redo') ? opt('--redo') : '');
    const missing = jobs.filter(j => !fs.existsSync(file(j)) && j.stem.startsWith(only));
    const est = Math.round(missing.reduce((s, j) => s + j.secs * 10, 0));
    console.log(`${jobs.length - jobs.filter(j => !fs.existsSync(file(j))).length}/${jobs.length} sounds rendered; ${missing.length} missing (~${est} credits).`);
    if (!args.includes('--render') && !opt('--redo')) { writeData(); return; }
    let spent = 0, failed = 0;
    const queue = missing.slice();
    await Promise.all([0, 1, 2].map(async () => {
        while (queue.length) {
            const j = queue.shift();
            try { spent += await render(j); process.stdout.write('.'); }
            catch (e) {
                failed++; console.log('\nFAILED ' + j.stem + ': ' + e.message);
                if (/^(401|402|403|429)/.test(e.message)) queue.length = 0;
            }
        }
    }));
    console.log(`\nSpent ${spent} credits; ${failed} failed. data/sfx-el.js lists ${writeData()} files.`);
}

main().catch(e => { console.error(e.message); process.exit(1); });
