/* A fixed teaching match: every practice move is legal in the normal engine. */
(function(root){
    'use strict';
    const Rift=root.Rift, Battle=Rift.Battle||(Rift.Battle={});
    const steps=[
        {title:'Your turn has a budget',text:'Look at Energy and Actions. You start with 1 energy and 3 actions. Play, attack, activate and rewrite each use an action. End turn hands play to Granny. This learning match has just 1 heart each; normal matches start with 6.',label:'Read my turn budget',actions:[]},
        {title:'Pay to play',text:'Astrophysicat costs 1 energy. Click it in your hand. It joins your board. You still have your turn and 2 actions, but no energy. New creatures may block; they attack or activate next turn.',label:'Play Astrophysicat',actions:[{type:'play',cid:'p0c0'}]},
        {title:'End and refill',text:'Click End turn. Granny will play a creature and end her turn. Your next turn brings 2 energy, a new card and 3 fresh actions. Energy does not carry over.',label:'End turn',actions:[{type:'end'},{type:'play',cid:'p1c0'},{type:'end'}]},
        {title:'Attack and exhaust',text:'Astrophysicat is ready. Attack costs no energy, but uses an action and exhausts it. Granny will block with Speedcheeta. Reason gains +2 against Emotion: 6 beats 4. Read the result; your turn continues.',label:'Attack with Astrophysicat',actions:[{type:'attack',cid:'p0c0'},{type:'block',cid:'p1c0'}]},
        {title:'Use another action',text:'You can still act this turn. Play Zuckerborg for 1 energy. Astrophysicat stays exhausted; Zuckerborg may block. Saving a ready creature can protect your hearts.',label:'Play Zuckerborg',actions:[{type:'play',cid:'p0c1'}]},
        {title:'Choose when to stop',text:'You have one action left. You can stop early rather than spend everything. End turn. Granny will play Lobstorian; then your energy grows to 3 and your creatures become ready.',label:'End turn',actions:[{type:'end'},{type:'play',cid:'p1c1'},{type:'end'}]},
        {title:'Pay for an ability',text:'Activate Astrophysicat for 2 energy. Its ability draws a card. Activating uses an action and exhausts the creature, so it cannot attack or block until your next turn.',label:'Activate Astrophysicat',actions:[{type:'activate',cid:'p0c0',ability:'well-actually'}]},
        {title:'Keep a blocker ready',text:'Zuckerborg is still ready. End turn. Granny will attack with Lobstorian. This time choose a blocker instead of losing your heart.',label:'End turn',actions:[{type:'end'},{type:'attack',cid:'p1c1'}]},
        {title:'Block a stronger creature',text:'Click Zuckerborg to block. Its 3 power gets +2 from the colour wheel, but 5 still loses to Lobstorian’s 6. The block saves your heart. Zuckerborg’s passive ability returns it to your hand once. Granny then plays a fresh Lobstorian for the next example.',label:'Block with Zuckerborg',actions:[{type:'block',cid:'p0c1'},{type:'play',cid:'p1c3'},{type:'end'}]},
        {title:'Spend energy to change a rule',text:'Pay 2 energy and 1 action to choose Underdog. Both players now use “weaker wins”. It stays until another combat rule replaces it or the timeline resets. Other rule categories stay as they were.',label:'Rewrite: Underdog',actions:[{type:'rewrite',choice:'underdog'}]},
        {title:'Same cards, different winner',text:'Attack with Astrophysicat. Its 4 power now beats Lobstorian’s 6 because Underdog is active. Granny will block so you can see the rule work. A large monster does not always win.',label:'Attack under Underdog',actions:[{type:'attack',cid:'p0c0'},{type:'block',cid:'p1c3'}]},
        {title:'Spend your last action',text:'Play Speedcheeta for 1 energy. This is your third action, so you must end after it. You cannot attack again with exhausted Astrophysicat.',label:'Play Speedcheeta',actions:[{type:'play',cid:'p0c2'}]},
        {title:'Watch the Fate track',text:'End turn. Granny will spend 3 energy on Muskrat. Normal matches mix ten axioms from each player. The central Fate track counts down: six End turns to a free flip, then six to a reset. Filter advances it; Next Year delays it. This lesson pauses automatic events.',label:'End turn',actions:[{type:'end'},{type:'play',cid:'p1c2'},{type:'end'}]},
        {title:'The victory rule can change too',text:'Pay 2 energy to change the victory rule. Now reaching YOUR OWN zero hearts wins. Underdog remains active: victory and combat are different categories. Read the bright victory warning before attacking.',label:'Rewrite: own zero hearts wins',actions:[{type:'rewrite',choice:'reverse-hearts'}]},
        {title:'Reason from the new goal',text:'End turn. Granny will attack with Muskrat. You could block, but your goal is now to lose your last heart. Your next choice will win through the new rule.',label:'End turn',actions:[{type:'end'},{type:'attack',cid:'p1c2'}]},
        {title:'Win by the current rules',text:'Choose Take the hit. Your own heart reaches zero, so YOU win under this victory rule. Normally that same choice would lose. Always read Rules now, your budget and the timeline.',label:'Take hit — win at zero hearts',actions:[{type:'take'}]},
    ];
    function team(ids,prefix){return ids.map((species,i)=>({uid:prefix+i,species,loaner:true,injuries:[]}));}
    function starter(){return team(['astrophysicat','zuckerborg','speedcheeta','lobstorian','muskrat','astrophysicat','zuckerborg','speedcheeta','lobstorian','muskrat'],'lesson-you-');}
    function create(){return Battle.Engine.createBattle({seed:'card-cycle-lesson',players:[{name:'You',team:starter()},{name:'Granny Axiom',team:team(['speedcheeta','lobstorian','muskrat','lobstorian','zuckerborg','speedcheeta','lobstorian','muskrat','astrophysicat','zuckerborg'],'lesson-granny-')}],axiomDeck:['underdog','reverse-hearts','two-actions','mercy'],options:{mode:'practice',lives:1,first:0,shuffle:false,shuffleAxioms:false,timeline:false}});}
    function advance(state,index){if(!steps[index])throw Error('Unknown lesson step');return steps[index].actions.reduce((s,a)=>Battle.Engine.applyAction(s,a),state);}
    Battle.Lesson={steps,create,advance,starter,team};
})(typeof window!=='undefined'?window:globalThis);
